### LOS GET's
GET http://localhost:2812/
### Llamar a todos los animales
GET http://localhost:2812/animals
### Buscar por id
GET http://localhost:2812/animals/3
### Filtrar por Familia "family": "Felidae" y peso mayo q
GET http://localhost:2812/animals/search?nombre_comun=Jaguar

### POST POST POST POST POST
### Para crear un animal
POST http://localhost:2812/animals
Content-Type: application/json

{
  "sql" : "drop table animals",
  "name": "Pablo",
  "species": "Homo",
  "family": "Campos",
  "habitat": "La u",
  "weight_kg": 65,
  "height_cm": 172,
  "image": "https://scontent.fjau1-1.fna.fbcdn.net/v/t39.30808-6/341380074_1338483886729660_4865480858772963586_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=6ee11a&_nc_ohc=WOB92kbwG-UQ7kNvgFdxcEG&_nc_zt=23&_nc_ht=scontent.fjau1-1.fna&_nc_gid=L5TaT_l377Qa9Nc5UmA80w&oh=00_AYHXZNsf8OQ7apFlMhDGg4UUWpjpS7wo4lN4c6qvloUAbQ&oe=67F0027C"
}

### Actualizar un animal
PATCH http://localhost:2812/animals/1
Content-Type: application/json

{
  "name":"JOSEF ORE",
  "species": "cat"
}
### Borrar un animal por id
DELETE http://localhost:2812/animals/1

### Actualizar datos update
PATCH http://localhost:2812/animals/4
Content-Type: application/json

{
  "name" : "name 2",
  "species": "AWDDAW"
}